export { default as Camera } from './Camera'
export { default as Edit2 } from './Edit2'
export { default as Logo } from './Logo'
export { default as MessageCircle } from './MessageCircle'
export { default as Phone } from './Phone'
export { default as Search } from './Search'
export { default as Settings } from './Settings'
export { default as Target } from './Target'